Repository truenas/ScaleAutomation, pull requests merged in 2024-04, with the labels that each got.

#217 TE-1629 / 24.10 - Local Groups Click Interception fix
  test_cases/webui/local_groups/test_local_groups.py
Labels: ported

#218 TE-1503 / TE-1504 / 24.04.0 / Replication NAS-T1154/NAS-T1269
  .idea/csv-editor.xml
  keywords/api/post.py
  keywords/ssh/common.py
  keywords/ssh/smb.py
  keywords/webui/replication.py
  test_cases/webui/replicate/conftest.py
  test_cases/webui/replicate/test_create_replication_task_different_box.py
  test_cases/webui/replicate/test_create_replication_task_same_box.py
  test_cases/webui/shares/smb/test_ad_user_can_connect_to_new_smb_share.py
  test_cases/webui/shares/smb/test_connect_to_new_smb_share.py
  test_cases/webui/ssh/test_rsync_connections.py
Labels: port-to-electric-eel

#222 TE-1658 / 24.10 / Builtin user/group test refactor
  test_cases/webui/local_groups/test_builtin_groups.py
  test_cases/webui/local_groups/test_local_groups.py
  test_cases/webui/local_users/test_builtin_users.py
  test_cases/webui/local_users/test_local_users.py
Labels: ported

#221 TE-1658 / 24.04.0 / Builtin user/group test refactor
  test_cases/webui/local_groups/test_builtin_groups.py
  test_cases/webui/local_groups/test_local_groups.py
  test_cases/webui/local_users/test_builtin_users.py
  test_cases/webui/local_users/test_local_users.py
Labels: port-to-electric-eel, ported

#225 TE-1489 / 24.10 / NFS maproot User and Group Testcase
  .gitignore
  keywords/ssh/nfs.py
  keywords/webui/nfs.py
  test_cases/webui/shares/nfs/test_advanced_configurations.py
  test_data/shares/nfs_advanced_config.csv
Labels: ported

#226 Pipeline fixes - SSH Rsync
  .idea/csv-editor.xml
  keywords/ssh/common.py
  keywords/webui/rsync.py
  test_cases/webui/shares/smb/test_connect_to_new_smb_share.py
  test_cases/webui/ssh/conftest.py
  test_cases/webui/ssh/test_rsync_connections.py
Labels: port-to-electric-eel

#227 TE-1503/24.10.0/Pipeline-fixes for Rsync
  .idea/csv-editor.xml
  keywords/ssh/common.py
  keywords/webui/rsync.py
  test_cases/webui/shares/smb/test_connect_to_new_smb_share.py
  test_cases/webui/ssh/conftest.py
  test_cases/webui/ssh/test_rsync_connections.py
Labels: ported

#228 TE-1506/24.10.0/added Adv Replicate to other pool-NAS-T1671
  keywords/api/post.py
  test_cases/webui/replicate/conftest.py
  test_cases/webui/replicate/test_create_adv_replication_task_same_box_different_pool.py
Labels: ported

#230 TE-1660/24.04.0/Bring advanced NFS configuration test case descriptions up to standard
  test_cases/webui/shares/nfs/test_advanced_configurations.py
Labels: ported

#229 TE-1660/24.10/Bring advanced NFS configuration test case descriptions up to standard
  test_cases/webui/shares/nfs/test_advanced_configurations.py
Labels: backport-to-dragonfish, ported

#231 Pipeline fixes
  test_cases/webui/ssh/test_ssh_connections.py
Labels: port-to-electric-eel, ported

#232 Pipeline-fixes-EE-port
  test_cases/webui/ssh/test_ssh_connections.py
Labels: ported

#233 TE-1659/24.04.0/pipeline fix Replication
  test_cases/webui/ssh/conftest.py
  test_cases/webui/ssh/test_rsync_connections.py
Labels: port-to-electric-eel, ported

#234 TE-1659/24.10.0/pipeline fix Replication
  test_cases/webui/ssh/conftest.py
  test_cases/webui/ssh/test_rsync_connections.py
Labels: ported

#239 TE-1702/24.10/remove flakey delete ix-applications in datasets
  test_cases/webui/datasets/test_dataset_roles.py
  test_cases/webui/datasets/test_dataset_tree.py
Labels: backport-to-dragonfish, ported

#240 TE-1702/24.04.0/remove flakey delete ix-applications in datasets
  test_cases/webui/datasets/test_dataset_roles.py
  test_cases/webui/datasets/test_dataset_tree.py
Labels: ported

#241 TE-1710/24.04.0/pipeline fix Apps WG-Easy
  keywords/webui/replication.py
  test_cases/webui/apps/wg_easy/test_edit_wg_easy.py
  test_cases/webui/replicate/test_create_replication_task_different_box.py
Labels: port-to-electric-eel, ported

#242 TE-1710/24.10.0/pipeline fix Apps WG-Easy
  keywords/webui/replication.py
  test_cases/webui/apps/wg_easy/test_edit_wg_easy.py
  test_cases/webui/replicate/test_create_replication_task_different_box.py
Labels: ported

#243 TE-1709/24.04.0/SSH Regression fixes
  keywords/webui/rsync.py
  keywords/webui/ssh_connection.py
  test_cases/webui/ssh/test_ssh_connections.py
Labels: port-to-electric-eel, ported

#245 TE-1709/24.10/SSH Regression fixes
  keywords/webui/rsync.py
  keywords/webui/ssh_connection.py
  test_cases/webui/ssh/test_ssh_connections.py
Labels: ported

#246 TE-1659/24.04.0/pipeline fix Replication
  test_cases/webui/replicate/test_create_adv_replication_task_same_box_different_pool.py
Labels: port-to-electric-eel, ported

#247 TE-1659/24.10.0/pipeline fix Replication
  test_cases/webui/replicate/test_create_adv_replication_task_same_box_different_pool.py
Labels: ported

#244 TE-1648/24.10/Add tear down class to NFS Advanced Config
  test_cases/webui/shares/nfs/test_advanced_configurations.py
Labels: no-port

#248 TE-1708/24.04.0/POSIX preset progress spinner click intercept fix
  keywords/webui/common.py
  test_cases/webui/datasets_permissions/posix_permissions/test_posix_custom_preset.py
  test_cases/webui/datasets_permissions/posix_permissions/test_posix_presets.py
Labels: port-to-electric-eel, ported

#250 TE-1709/24.04.0/pipeline fix SSH and SMB
  test_cases/webui/shares/smb/test_delete_new_smb_share.py
  test_cases/webui/ssh/test_ssh_connections.py
Labels: port-to-electric-eel, ported

#251 TE-1709/24.10.0/pipeline fix SSH and SMB
  test_cases/webui/shares/smb/test_delete_new_smb_share.py
  test_cases/webui/ssh/test_ssh_connections.py
Labels: ported

#253 TE-1709/24.04.0/pipeline fix SSH timing
  keywords/webui/ssh_connection.py
Labels: port-to-electric-eel, ported

#254 TE-1709/24.10.0/pipeline fix SSH timing
  keywords/webui/ssh_connection.py
Labels: ported

#255 TE-1659/24.04.0/pipeline fix Replication
  keywords/webui/replication.py
  test_cases/webui/replicate/test_create_replication_task_different_box.py
Labels: port-to-electric-eel, ported

#256 TE-1659/24.10.0/pipeline fix Replication
  keywords/webui/replication.py
  test_cases/webui/replicate/test_create_replication_task_different_box.py
Labels: ported

#257 TE-1714/24.04.0/Add spinner assert to delete dataset
  keywords/webui/datasets.py
Labels: port-to-electric-eel

#260 TE-1715/24.10.0/pipeline fix SMB
  test_cases/webui/shares/smb/test_ad_user_can_connect_to_new_smb_share.py
Labels: ported

#259 TE-1715/24.04.0/pipeline fix SMB
  test_cases/webui/shares/smb/test_ad_user_can_connect_to_new_smb_share.py
Labels: port-to-electric-eel, ported

#263 TE-1717/24.04.0/Apps Timing fixes
  keywords/webui/apps.py
Labels: port-to-electric-eel, ported

#264 TE-1717/24.10/Apps Timing fixes
  keywords/webui/apps.py
Labels: ported

#261 TE-1716/24.04.0/Update Recursive POSIX test for NAS-128091 fix
  keywords/ssh/permissions.py
  keywords/webui/permissions.py
  test_cases/webui/datasets_permissions/posix_permissions/test_posix_recursive_permissions.py
  test_data/dataset_permission/posix_acl_recursive_permissions.csv
Labels: port-to-electric-eel, ported

#262 TE-1716/24.10/Update Recursive POSIX test for NAS-128091 fix
  keywords/ssh/permissions.py
  keywords/webui/permissions.py
  test_cases/webui/datasets_permissions/posix_permissions/test_posix_recursive_permissions.py
  test_data/dataset_permission/posix_acl_recursive_permissions.csv
Labels: ported

#266 TE-1659/24.10.0/pipeline fix Replication
  test_cases/webui/replicate/conftest.py
  test_cases/webui/replicate/test_create_replication_task_different_box.py
Labels: ported

#267 TE-1721/24.04.0/Add while loop to SSH key file find
  keywords/webui/common.py
  keywords/webui/ssh_connection.py
Labels: port-to-electric-eel, ported

#268 TE-1721/24.10.0/Add while loop to SSH key file find
  keywords/webui/common.py
  keywords/webui/ssh_connection.py
Labels: ported

#271 TE-1715/24.10.0/pipeline fix SMB
  keywords/api/put.py
Labels: no-port

#270 TE-1648/24.04.0/Add view all click to advanced config setup
  test_cases/webui/shares/nfs/test_nfs_share_advanced_configurations.py
Labels: ported

#269 TE-1648/24.10.0/Add view all click to advanced config setup
  test_cases/webui/shares/nfs/test_nfs_share_advanced_configurations.py
Labels: backport-to-dragonfish, ported
