Repository truenas/ScaleAutomation, pull requests merged in 2024-06, with the labels that each got.

#336 TEN-1331/TEN-1354 / 24.10 / Fix certificates deletion dialog handling
  keywords/webui/certificates.py
Labels: ported

#338 TEN-1035/24.04.2/pipeline add Read-Only Admin Share Admin System Settings Advanced tests
  test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_system_settings_advanced.py
  test_cases/webui/restricted_admin/share-admin/test_share_admin_system_settings_advanced.py
  xpaths/__init__.py
  xpaths/system.py
Labels: port-to-electric-eel, ported

#340 Refactor is visible
  keywords/webui/common.py
  test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_system_settings_advanced.py
  test_cases/webui/restricted_admin/share-admin/test_share_admin_system_settings_advanced.py
Labels: port-to-electric-eel, ported

#341 Refactor is visible ee
  keywords/webui/common.py
  test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_system_settings_advanced.py
  test_cases/webui/restricted_admin/share-admin/test_share_admin_system_settings_advanced.py
Labels: ported

#344 TEN-1359/24.10.0/pipeline add Read-Only Admin Share Admin Cloud Sync tests
  keywords/api/put.py
  test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_cloud_sync_tasks.py
  test_cases/webui/restricted_admin/share-admin/test_share_admin_cloud_sync_tasks.py
Labels: ported

#343 TEN-1360/24.04.2/pipeline add Read-Only Admin Share Admin Cloud Sync tests
  keywords/api/put.py
  test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_cloud_sync_tasks.py
  test_cases/webui/restricted_admin/share-admin/test_share_admin_cloud_sync_tasks.py
Labels: port-to-electric-eel, ported

#345 TEN-1357/TEN-1358 / 24.10 / Refactor Sharing to Shares
  keywords/webui/common_shares.py
  keywords/webui/iscsi.py
  keywords/webui/navigation.py
  keywords/webui/nfs.py
  keywords/webui/smb.py
  xpaths/__init__.py
  xpaths/shares.py
Labels: no-port

#346 TEN-1315/24.10.0/pipeline add Share Admin Shares tests
  keywords/webui/nfs.py
  keywords/webui/smb.py
  test_cases/webui/restricted_admin/share-admin/test_share_admin_shares.py
Labels: no-port

#349 TEN-1341 / 24.10 / Rename relevant NFS methods to specify v3 or v4
  test_cases/webui/shares/nfs/test_create_new_nfs_share.py
  test_cases/webui/shares/nfs/test_delete_new_nfs_share.py
  test_cases/webui/shares/nfs/test_edit_nfs_share.py
  test_cases/webui/shares/nfs/test_nfsv3_share_advanced_configurations.py
Labels: backport-to-dragonfish

#350 TEN-1341 / 24.04.2 / Rename relevant NFS methods to specify v3 or v4
  test_cases/webui/shares/nfs/test_create_new_nfs_share.py
  test_cases/webui/shares/nfs/test_delete_new_nfs_share.py
  test_cases/webui/shares/nfs/test_edit_nfs_share.py
  test_cases/webui/shares/nfs/test_nfsv3_share_advanced_configurations.py
Labels: ported

#351 TEN-1040/24.04.2/pipeline add Read-Only Admin Alert Settings tests
  keywords/webui/alert_settings.py
  keywords/webui/common.py
  keywords/webui/navigation.py
  test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_system_settings_alert_settings.py
Labels: port-to-electric-eel, ported

#352 TEN-1040/24.10.0/pipeline add Read-Only Admin Alert Settings tests
  keywords/webui/alert_settings.py
  keywords/webui/common.py
  keywords/webui/navigation.py
  test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_system_settings_alert_settings.py
  xpaths/common_xpaths.py
Labels: ported

#353 TEN-1363/24.10.0/refacter is restricted method code
  keywords/webui/common.py
Labels: no-port

#356 TEN-1370/24.04.2/pipeline add Read-Only Admin Iscsi Share tests
  keywords/webui/common_shares.py
  keywords/webui/iscsi.py
  test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_iscsi_share.py
Labels: no-port

#365 TEN-1370/24.04.2/pipeline fix infinite loop on replication
  keywords/webui/common.py
  test_cases/webui/replicate/test_create_replication_task_different_box.py
Labels: port-to-electric-eel

#366 TEN-1363/24.10.0/pipeline refactor restricted toggle
  keywords/webui/common.py
  keywords/webui/common_shares.py
  keywords/webui/data_protection.py
  keywords/webui/nfs.py
  keywords/webui/smb.py
  test_cases/webui/dashboard/test_system_information_card_copy_version_to_clipboard.py
  test_cases/webui/dashboard/test_system_information_card_ui.py
  test_cases/webui/dashboard/test_the_check_for_update_button_on_the_dashboard.py
  test_cases/webui/dashboard/test_the_report_button_on_the_storage_card.py
  test_cases/webui/replicate/test_create_replication_task_different_box.py
  test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_cloud_sync_tasks.py
  test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_nfs_share.py
  test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_periodic_snapshot_tasks.py
  test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_replication_tasks.py
  test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_rsync_tasks.py
  test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_scrub_tasks.py
  test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_smb_share.py
  test_cases/webui/restricted_admin/share-admin/test_share_admin_cloud_sync_tasks.py
  test_cases/webui/restricted_admin/share-admin/test_share_admin_periodic_snapshot_tasks.py
  test_cases/webui/restricted_admin/share-admin/test_share_admin_rsync_tasks.py
  test_cases/webui/restricted_admin/share-admin/test_share_admin_scrub_tasks.py
  test_cases/webui/shares/nfs/test_delete_new_nfs_share.py
Labels: no-port

#368 TEN-1419/24.04.2/pipeline fix Read-Only Admin Iscsi Share tests
  keywords/webui/common_shares.py
Labels: no-port

#371 TEN-1422 / 24.04.2 / NFS share tests not waiting on progress bar
  test_cases/webui/shares/nfs/test_create_new_nfs_share.py
  test_cases/webui/shares/nfs/test_edit_nfs_share.py
  test_cases/webui/shares/nfs/test_nfs_share_path_ui_errors.py
Labels: port-to-electric-eel, ported

#372 TEN-1422 / 24.10 / NFS share tests not waiting on progress bar
  test_cases/webui/shares/nfs/test_create_new_nfs_share.py
  test_cases/webui/shares/nfs/test_edit_nfs_share.py
  test_cases/webui/shares/nfs/test_nfs_share_path_ui_errors.py
Labels: ported

#373 TEN-1423 / 24.10 / Replace UI reboot with API reboot
  keywords/api/post.py
  test_cases/webui/dashboard/test_system_information_card_uptime_resets_on_reboot.py
  test_cases/webui/shares/smb/test_ad_user_can_connect_to_new_smb_share.py
  test_cases/webui/system_settings/services/test_system_services.py
Labels: no-port

#374 TEN-1366/24.10.0/Redesign Replication - Remote
  keywords/api/common.py
  keywords/api/post.py
  keywords/webui/advanced.py
  keywords/webui/common.py
  keywords/webui/data_protection.py
  keywords/webui/datasets.py
  keywords/webui/replication.py
  keywords/webui/smb.py
  test_cases/webui/replicate/conftest.py
  test_cases/webui/replicate/test_create_adv_replication_task_same_box_different_pool.py
  test_cases/webui/replicate/test_create_replication_task_different_box.py
  test_cases/webui/replicate/test_create_replication_task_local_box.py
  test_cases/webui/replicate/test_create_replication_task_remote_box.py
  test_cases/webui/replicate/test_create_replication_task_same_box.py
  test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_periodic_snapshot_tasks.py
  test_cases/webui/restricted_admin/share-admin/test_share_admin_periodic_snapshot_tasks.py
  test_data/replication.csv
  xpaths/datasets.py
Labels: no-port

#378 TEN-1381 / 24.04.2 / Add group cache disabled AD configuration coverage
  keywords/webui/active_directory.py
  keywords/webui/directory_services.py
  keywords/webui/smb.py
  test_cases/webui/active_directory/test_active_directory.py
  xpaths/smb.py
Labels: ported

#382 TEN-1366/24.10.0/Redesign Replication - replicate simplify
  keywords/api/get.py
  keywords/api/post.py
  keywords/webui/replication.py
  test_cases/webui/replicate/conftest.py
  test_cases/webui/replicate/test_create_replication_task_local_box.py
  test_cases/webui/replicate/test_create_replication_task_remote_box.py
Labels: no-port

#384 Ten 1428
  conftest.py
  helper/webui.py
Labels: no-port

#383 TEN-1038/24.10.0/pipeline add Share Admin Services tests
  keywords/api/post.py
  keywords/webui/common.py
  test_cases/webui/restricted_admin/share-admin/test_share_admin_system_settings_services.py
Labels: no-port

#385 TEN-1429 / 24.10 / fixing pylint TODO and Allure issues
  keywords/webui/certificates.py
  keywords/webui/common.py
  keywords/webui/data_protection.py
  test_cases/webui/datasets_permissions/nfsv4_permissions/test_create_dataset_with_nfsv4_acl.py
  test_cases/webui/datasets_permissions/posix_permissions/test_posix_custom_preset.py
  test_cases/webui/datasets_permissions/posix_permissions/test_posix_presets.py
  test_cases/webui/datasets_permissions/posix_permissions/test_posix_recursive_permissions.py
  test_cases/webui/datasets_permissions/unix_permissions/test_unix_permissions.py
  test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_replication_tasks.py
  test_cases/webui/shares/nfs/test_edit_nfs_share.py
Labels: no-port

#386 TEN-1321 / 24.10 / comment out percy calls causing hanging
  conftest.py
  test_cases/webui/active_directory/test_active_directory.py
  test_cases/webui/dashboard/test_default_dashboard_cards_are_visible.py
  test_cases/webui/datasets/test_create_dataset.py
  test_cases/webui/local_users/test_local_users.py
  test_cases/webui/login/test_login_page_ui.py
  test_cases/webui/storage/test_storage_dashboard.py
Labels: no-port

#388 TEN-1431/24.10.0/pipeline fix RO Datasets, RO and Share Admin Boot tests
  keywords/webui/boot.py
  test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_boot_environments.py
  test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_dataset.py
  test_cases/webui/restricted_admin/share-admin/test_share_admin_boot_environments.py
  test_data/read_only_admin_dataset.csv
Labels: no-port

#391 TEN-1069/24.10.0/replication encrypted to unencrypted tests
  keywords/webui/replication.py
  test_cases/webui/replicate/test_replication_task_encryption.py
  xpaths/datasets.py
Labels: no-port

#393 TEN-1075/24.10.0/replication download logs tests
  keywords/webui/common.py
  keywords/webui/replication.py
  test_cases/webui/replicate/test_create_replication_task_remote_box.py
Labels: no-port
