Repository truenas/ScaleAutomation, pull requests merged in 2024-07, with the labels that each got.

#395 TEN-1435 / 24.04.2 / comment out percy lines causing hanging
  conftest.py
  test_cases/webui/dashboard/test_default_dashboard_cards_are_visible.py
Labels: no-port

#396 TEN-1379 / 24.10.0 / SSH Shell control
  helper/cli.py
  keywords/webui/common.py
  keywords/webui/ssh_connection.py
  test_cases/webui/ssh/test_ssh_shell_access.py
  test_data/ssh_shell_access.csv
  xpaths/local_users.py
Labels: no-port

#397 TEN-1437/TEN-1439/TEN-1440 / 24.10.0 / Fix logout button location, Fix copyright text handling
  keywords/webui/common.py
  test_cases/webui/login/test_login_page_ui.py
Labels: no-port

#398 TEN-1321 / 24.10 / Adding back percy and added code to avoid starting percy if not installed
  conftest.py
  helper/reporting.py
  test_cases/webui/active_directory/test_active_directory.py
  test_cases/webui/dashboard/test_default_dashboard_cards_are_visible.py
  test_cases/webui/datasets/test_create_dataset.py
  test_cases/webui/local_users/test_local_users.py
  test_cases/webui/login/test_login_page_ui.py
  test_cases/webui/storage/test_storage_dashboard.py
Labels: no-port

#399 TEN-1438 / 24.04.2 / Increase execution delay to 30 ms, add tab=True to click dataset method
  keywords/webui/datasets.py
  profiles/shared.toml
Labels: ported

#400 TEN-1428 / 24.10.0 / Increase execution delay from 10 to 30 milliseconds
  profiles/shared.toml
Labels: backport-to-dragonfish, ported
