Repository truenas/ScaleAutomation, pull requests merged in 2024-05, with the labels that each got.

#272 TE-1464/24.04.0/pipeline fix Read Only Admin Scrub Task
  keywords/api/delete.py
  keywords/api/post.py
  keywords/webui/common.py
  keywords/webui/data_protection.py
  test_cases/webui/permissions/read-only-admin/test_read_only_admin_scrub_tasks.py
  xpaths/__init__.py
  xpaths/data_protection.py
Labels: port-to-electric-eel, ported

#273 TE-1464/24.10.0/pipeline fix Read Only Admin Scrub Task
  keywords/api/common.py
  keywords/api/delete.py
  keywords/api/get.py
  keywords/api/post.py
  keywords/webui/common.py
  keywords/webui/data_protection.py
  test_cases/webui/permissions/read-only-admin/test_read_only_admin_scrub_tasks.py
  xpaths/__init__.py
  xpaths/data_protection.py
Labels: ported

#276 TE-1465/24.04.0/pipeline fix Read Only Admin Cloud Sync Task
  keywords/api/delete.py
  keywords/api/post.py
  keywords/api/put.py
  keywords/webui/common.py
  keywords/webui/data_protection.py
  test_cases/webui/permissions/read-only-admin/test_read_only_admin_cloud_sync_tasks.py
  test_data/.gitignore
  xpaths/data_protection.py
Labels: port-to-electric-eel, ported

#277 TE-1465/24.10.0/pipeline fix Read Only Admin Cloud Sync Task
  keywords/api/delete.py
  keywords/api/post.py
  keywords/api/put.py
  keywords/webui/common.py
  keywords/webui/data_protection.py
  test_cases/webui/permissions/read-only-admin/test_read_only_admin_cloud_sync_tasks.py
  test_data/.gitignore
  xpaths/data_protection.py
Labels: ported

#280 TEN-1140/24.10.0/Refactor System Services for EE
  keywords/api/post.py
  keywords/webui/common_shares.py
  keywords/webui/nfs.py
  keywords/webui/smb.py
  keywords/webui/system_services.py
  test_cases/webui/system_settings/services/test_system_services.py
Labels: port-to-dragonfish

#282 24.10.0/rename permissions to restricted_admin
  test_cases/webui/restricted_admin/read-only-admin/conftest.py
  test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_cloud_sync_tasks.py
  test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_dataset.py
  test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_iscsi_share.py
  test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_nfs_share.py
  test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_scrub_tasks.py
  test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_smb_share.py
  test_cases/webui/restricted_admin/share-admin/conftest.py
  test_cases/webui/restricted_admin/share-admin/test_share_admin_cloud_sync_tasks.py
  test_cases/webui/restricted_admin/share-admin/test_share_admin_scrub_tasks.py
Labels: port-to-dragonfish, ported

#283 24.04.0/rename permissions to restricted_admin
  test_cases/webui/restricted_admin/read-only-admin/conftest.py
  test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_cloud_sync_tasks.py
  test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_dataset.py
  test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_iscsi_share.py
  test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_nfs_share.py
  test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_scrub_tasks.py
  test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_smb_share.py
  test_cases/webui/restricted_admin/share-admin/conftest.py
  test_cases/webui/restricted_admin/share-admin/test_share_admin_cloud_sync_tasks.py
  test_cases/webui/restricted_admin/share-admin/test_share_admin_scrub_tasks.py
Labels: ported

#284 TEN-1137/24.10.0/Datasets Permissions EE refactor
  helper/webui.py
  keywords/webui/datasets.py
  keywords/webui/navigation.py
  test_cases/webui/datasets_permissions/posix_permissions/test_posix_recursive_permissions.py
Labels: no-port

#285 TEN-1138/24.10.0/fix backend service call on shares page
  keywords/webui/common_shares.py
Labels: no-port

#286 TEN-1022/24.04.0/pipeline fix Read Only Admin Periodic Snapshot Task
  keywords/api/delete.py
  keywords/api/put.py
  keywords/webui/data_protection.py
  test_cases/webui/restricted_admin/read-only-admin/conftest.py
  test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_periodic_snapshot_tasks.py
  xpaths/data_protection.py
Labels: port-to-electric-eel, ported

#287 TEN-1022/24.10.0/pipeline fix Read Only Admin Periodic Snapshot Task
  keywords/api/delete.py
  keywords/api/put.py
  keywords/webui/data_protection.py
  test_cases/webui/restricted_admin/read-only-admin/conftest.py
  test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_periodic_snapshot_tasks.py
  xpaths/data_protection.py
Labels: ported

#288 TEN-1022/24.10.0/pipeline fix Share Admin Periodic Snapshot Task
  test_cases/webui/restricted_admin/share-admin/test_share_admin_periodic_snapshot_tasks.py
  xpaths/common_xpaths.py
Labels: ported

#289 TEN-1022/24.04.0/pipeline fix Share Admin Periodic Snapshot Task
  test_cases/webui/restricted_admin/share-admin/test_share_admin_periodic_snapshot_tasks.py
  xpaths/common_xpaths.py
Labels: port-to-electric-eel, ported

#290 TEN-1028/24.04.0/pipeline fix Read Only Admin Local Groups
  keywords/webui/local_groups.py
  test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_local_groups.py
  test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_periodic_snapshot_tasks.py
  test_cases/webui/restricted_admin/share-admin/test_share_admin_periodic_snapshot_tasks.py
Labels: port-to-electric-eel, ported

#291 TEN-1028/24.10.0/pipeline fix Read Only Admin Local Groups
  .idea/csv-editor.xml
  keywords/webui/local_groups.py
  test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_local_groups.py
  test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_periodic_snapshot_tasks.py
  test_cases/webui/restricted_admin/share-admin/test_share_admin_periodic_snapshot_tasks.py
Labels: ported

#292 TEN-1028/24.04.0/pipeline fix Share Admin Local Groups
  test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_cloud_sync_tasks.py
  test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_scrub_tasks.py
  test_cases/webui/restricted_admin/share-admin/test_share_admin_cloud_sync_tasks.py
  test_cases/webui/restricted_admin/share-admin/test_share_admin_local_groups.py
  test_cases/webui/restricted_admin/share-admin/test_share_admin_scrub_tasks.py
Labels: port-to-electric-eel, ported

#293 TEN-1028/24.10.0/pipeline fix Share Admin Local Groups
  test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_cloud_sync_tasks.py
  test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_scrub_tasks.py
  test_cases/webui/restricted_admin/share-admin/test_share_admin_cloud_sync_tasks.py
  test_cases/webui/restricted_admin/share-admin/test_share_admin_local_groups.py
  test_cases/webui/restricted_admin/share-admin/test_share_admin_scrub_tasks.py
Labels: ported

#296 TEN-1029/24.10.0/pipeline fix Read Only Admin Local Users
  keywords/webui/local_users.py
  test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_local_users.py
Labels: ported

#295 TEN-1029/24.04.0/pipeline fix Read Only Admin Local Users
  keywords/webui/local_users.py
  test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_local_users.py
Labels: port-to-electric-eel, ported

#298 TEN-1029/24.04.0/pipeline fix Share Admin Local Users
  test_cases/webui/restricted_admin/share-admin/test_share_admin_local_users.py
Labels: port-to-electric-eel, ported

#297 TEN-1029/24.10.0/pipeline fix Share Admin Local Users
  test_cases/webui/restricted_admin/share-admin/test_share_admin_local_users.py
Labels: ported

#294 TEN-1138/24.10.0/Update Restricted Admin Suite for EE
  keywords/webui/nfs.py
  keywords/webui/smb.py
  keywords/webui/snapshots.py
  test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_nfs_share.py
  test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_smb_share.py
  test_data/read_only_admin_shares.csv
  xpaths/common_xpaths.py
  xpaths/datasets.py
Labels: no-port

#299 TEN-1138/24.10.0/Update AD Suite for EE
  test_cases/webui/active_directory/test_active_directory.py
Labels: no-port

#302 TEN-1139 & TEN-1319 / 24.10 / SMB Suite Updates for EE
  keywords/webui/directory_services.py
  test_cases/webui/ldap/test_disable_ldap.py
  test_cases/webui/ldap/test_setup_ldap.py
  test_cases/webui/shares/smb/test_ad_user_can_connect_to_new_smb_share.py
Labels: backport-to-dragonfish

#303 TEN-1139 / 24.04.1 / remove_ldap speed increase
  keywords/webui/directory_services.py
Labels: ported

#304 TEN-1316 / 24.10 / Fix spinner failure, add timestamper
  keywords/webui/system_services.py
  pytest.ini
  requirements.txt
Labels: no-port

#305 TEN-1316 / 24.04.1 / Add wait for progress spinner, add timestamper plugin
  keywords/webui/system_services.py
  pytest.ini
  requirements.txt
Labels: ported

#306 TEN-1027/24.04.0/pipeline fix Share Admin Shares
  keywords/webui/common.py
  keywords/webui/common_shares.py
  test_cases/webui/restricted_admin/share-admin/test_share_admin_shares.py
  xpaths/sharing.py
Labels: port-to-electric-eel, ported

#307 TEN-1027/24.10.0/pipeline fix Share Admin Shares
  keywords/webui/common.py
  keywords/webui/common_shares.py
  test_cases/webui/restricted_admin/share-admin/test_share_admin_shares.py
  xpaths/sharing.py
Labels: ported

#309 TEN-1027/24.04.0/pipeline refactor Share Admin Shares
  keywords/webui/common.py
  keywords/webui/common_shares.py
  keywords/webui/iscsi.py
  keywords/webui/smb.py
  test_cases/webui/restricted_admin/share-admin/test_share_admin_shares.py
Labels: port-to-electric-eel, ported

#310 TEN-1027/24.10.0/pipeline refactor Share Admin Shares
  keywords/webui/common.py
  keywords/webui/common_shares.py
  keywords/webui/iscsi.py
  keywords/webui/smb.py
  test_cases/webui/restricted_admin/share-admin/test_share_admin_shares.py
Labels: ported

#312 012/24.10.0/pipeline fix Share Admin SMART test
  keywords/api/delete.py
  keywords/api/post.py
  keywords/webui/common.py
  keywords/webui/common_shares.py
  keywords/webui/data_protection.py
  test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_smart_tests.py
  test_cases/webui/restricted_admin/share-admin/test_share_admin_smart_tests.py
  xpaths/data_protection.py
Labels: ported

#317 TEN-1024/24.04.1/pipeline add Read-Only Admin Replication task tests
  keywords/api/delete.py
  keywords/api/post.py
  keywords/api/put.py
  keywords/webui/data_protection.py
  keywords/webui/replication.py
  test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_cloud_sync_tasks.py
  test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_replication_tasks.py
  xpaths/data_protection.py
Labels: port-to-electric-eel, ported

#320 TEN-1327 / 24.10 / Update SMB and SMART service xpaths
  keywords/webui/smb.py
  keywords/webui/system_services.py
Labels: no-port

#322 TEN-1024/24.04.0/pipeline add Read-Only Admin Replication task tests
  keywords/webui/data_protection.py
  test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_replication_tasks.py
Labels: port-to-electric-eel, ported

#323 TEN-1330 / 24.04.1 / Fix NFS/SMB service dialog handling
  helper/webui.py
  keywords/webui/common_shares.py
  keywords/webui/navigation.py
  test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_periodic_snapshot_tasks.py
  test_cases/webui/shares/nfs/test_create_new_nfs_share.py
  test_cases/webui/shares/nfs/test_edit_nfs_share.py
  test_cases/webui/shares/smb/conftest.py
  test_cases/webui/shares/smb/test_create_new_smb_share.py
  test_cases/webui/shares/smb/test_create_new_smb_share_with_acl.py
  test_cases/webui/shares/smb/test_create_new_smb_share_with_advanced_options.py
  test_cases/webui/shares/smb/test_create_new_smb_share_without_acl.py
  test_cases/webui/shares/smb/test_edit_smb_share.py
Labels: port-to-electric-eel

#330 TEN-1031/24.10.0/pipeline add Read-Only Admin Share Admin Backup Credential tests
  keywords/webui/backup_credentials.py
  keywords/webui/common.py
  keywords/webui/data_protection.py
  keywords/webui/replication.py
  test_cases/webui/replicate/conftest.py
  test_cases/webui/replicate/test_create_replication_task_different_box.py
  test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_backup_credential.py
  test_cases/webui/restricted_admin/share-admin/test_share_admin_backup_credential.py
  xpaths/__init__.py
  xpaths/backup_credentials.py
Labels: ported

#329 TEN-1031/24.04.1/pipeline add Read-Only Admin Share Admin Backup Credential tests
  keywords/webui/backup_credentials.py
  keywords/webui/common.py
  test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_backup_credential.py
  test_cases/webui/restricted_admin/share-admin/test_share_admin_backup_credential.py
  xpaths/__init__.py
  xpaths/backup_credentials.py
Labels: port-to-electric-eel, ported

#331 pylint EE fixes
  .github/workflows/pylint.yml
  keywords/api/dataset.py
  keywords/api/delete.py
  keywords/api/iscsi.py
  keywords/api/post.py
  keywords/ssh/nfs.py
  keywords/ssh/permissions.py
  keywords/ssh/smb.py
  keywords/ssh/zpool.py
  keywords/webui/apps.py
  keywords/webui/common_replication.py
  keywords/webui/common_shares.py
  keywords/webui/data_protection.py
  keywords/webui/datasets.py
  keywords/webui/local_groups.py
  keywords/webui/local_users.py
  keywords/webui/permissions.py
  keywords/webui/pool_creation_wizard.py
  keywords/webui/replication.py
  test_cases/webui/dashboard/test_cpu_card_text.py
  test_cases/webui/dashboard/test_links_in_truenas_help_card.py
  test_cases/webui/dashboard/test_the_report_button_on_the_cpu_card.py
  test_cases/webui/dashboard/test_the_report_button_on_the_memory_card.py
  test_cases/webui/dashboard/test_the_report_button_on_the_network_card.py
  test_cases/webui/datasets_permissions/nfsv4_permissions/test_nfsv4_presets.py
  test_cases/webui/datasets_permissions/posix_permissions/test_posix_presets.py
  test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_dataset.py
  test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_iscsi_share.py
  test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_nfs_share.py
  test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_rsync_tasks.py
  test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_scrub_tasks.py
  test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_smb_share.py
  test_cases/webui/restricted_admin/share-admin/test_share_admin_rsync_tasks.py
  test_cases/webui/shares/nfs/test_nfs_share_card_ui.py
  test_cases/webui/shares/smb/test_create_new_smb_share_with_advanced_options.py
  xpaths/apps.py
  xpaths/common_xpaths.py
  xpaths/datasets.py
Labels: no-port

#332 TEN-1016 / 24.04.1.1 / add RO Admin - Share Admin System Settings General tests
  .github/workflows/pylint.yml
  test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_system_settings_general.py
  test_cases/webui/restricted_admin/share-admin/test_share_admin_system_settings_general.py
Labels: port-to-electric-eel, ported

#334 TEN-1352/24.04.02/shares-admin-enabled-mismatch
  test_cases/webui/restricted_admin/share-admin/test_share_admin_shares.py
Labels: no-port
